/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CardComponent: typeof import('./components/CardComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeScreenComponent: typeof import('./components/HomeScreenComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./components/SearchComponent.vue')['default']
    TagSearchComponent: typeof import('./components/TagSearchComponent.vue')['default']
    TrendingComponent: typeof import('./components/TrendingComponent.vue')['default']
  }
}
